openapi: 3.0.0
info:
  title: SeraSmart
  version: 1.0.0
  
components:
  # Reusable schemas (data models)
  schemas:
    GadgetReadResponse:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: integer
            state:
              type: string
            timestamp:
              type: string
        status:
          type: string
        
    GadgetWriteResponse:
      type: object
      properties:
        status:
          type: string
    
    GadgetWrite:
      type: object
      properties:
        state:
          type: integer
    
    SensorRead:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: integer
            timestamp:
              type: string
            value:
              type: number
        status:
          type: string
          
          
    SensorStats:
      type: object
      properties:
        data:
          type: object
          properties:
            average:
              type: number
            history:
              type: array
              items: 
                type: number
        status:
          type: string
          
  
paths:
  /fereastra:
    get:
      description: Ia starea ferestrei 
      parameters:
        - in: query
          name: last_id
          required: true
          schema:
            type: integer
          description: Ultimul id inregistrat
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/GadgetReadResponse'
                
                
    post:
      description: Schimba starea ferestrei
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/GadgetWrite'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/GadgetWriteResponse'
                
  /usa:
    get:
      description: Ia starea usii 
      parameters:
        - in: query
          name: last_id
          required: true
          schema:
            type: integer
          description: Ultimul id inregistrat
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/GadgetReadResponse'
                
                
    post:
      description: Schimba starea usii 
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/GadgetWrite'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/GadgetWriteResponse'
                
                
  /temperatura:
    get:
      description: Ia valoarea curenta a sensorului 
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/SensorRead'
                
                
    post:
      description: Compileaza un istoric
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/SensorStats'
                
                
  /lumina:
    get:
      description: Ia valoarea curenta a sensorului 
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/SensorRead'
                
                
    post:
      description: Compileaza un istoric
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/SensorStats'
                
                
  /umiditate:
    get:
      description: Ia valoarea curenta a sensorului 
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/SensorRead'
                
                
    post:
      description: Compileaza un istoric
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/SensorStats' 