openapi: 3.0.0
info:
  title: SeraSmart
  version: 1.0.0
  
components:
  # Reusable schemas (data models)
  schemas:
    GadgetRead:
      type: object
      properties:
        data:
          type: object
          properties:
            id:
              type: integer
            state:
              type: string
            timestamp:
              type: string
        status:
          type: string
        
    GadgetWrite:
      type: object
      properties:
        status:
          type: string
  
paths:
  /fereastra:
    get:
      description: Ia starea ferestrei 
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/GadgetRead'
                
                
    post:
      description: Schimba starea ferestrei 
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/GadgetWrite'